
import Datos.vCargoExtra;
import Logica.cargoExtra;
import Logica.conexion;

import Logica.habitacion;
import Logica.fHabitacionesRecepcion_CargoExtra;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;



import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Leo21
 */
public class HabitacionesRecepcion_CargoExtra extends javax.swing.JFrame {
    
    
    

    /**
     * Creates new form HabitacionesRecepcion
     */
    public HabitacionesRecepcion_CargoExtra() {
        initComponents();
        
        
        cargoExtra ce = new cargoExtra();
        DefaultComboBoxModel modelCargoE = new DefaultComboBoxModel(ce.mostrarCargoExtra());
        cmbCargoExtra.setModel(modelCargoE);
        
        habitacion h = new habitacion();
        DefaultComboBoxModel modelHabitacion = new DefaultComboBoxModel(h.mostrarHabitacion());
        cmbHabitacion.setModel(modelHabitacion);
        
        
        
    }
    
    
    void ocultar_columna(){
        tablaListado.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaListado.getColumnModel().getColumn(0).setMinWidth(0);
        tablaListado.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        tablaListado.getColumnModel().getColumn(1).setMaxWidth(0);
        tablaListado.getColumnModel().getColumn(1).setMinWidth(0);
        tablaListado.getColumnModel().getColumn(1).setPreferredWidth(0);
        
        tablaListado.getColumnModel().getColumn(2).setMaxWidth(0);
        tablaListado.getColumnModel().getColumn(2).setMinWidth(0);
        tablaListado.getColumnModel().getColumn(2).setPreferredWidth(0);
    }
     
    void mostrar(int buscar){
        try {
            DefaultTableModel modelo;
            
            fHabitacionesRecepcion_CargoExtra func = new fHabitacionesRecepcion_CargoExtra();
            
            modelo = func.mostrar(buscar);
            
            tablaListado.setModel(modelo);
            ocultar_columna();
            lblTotalConsumo.setText("Consumo Total $. " + func.totalConsumo);
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
              
    }
    
    
    public void limpiar(){
        txtCargo_id.setText("");
        txtPrecioUnitario.setText("");
        txtCantidad.setText("");
        
       txtFecha.setText("");
        cmbCargoExtra.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListado = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbCargoExtra = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbHabitacion = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPrecioUnitario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCargo_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblTotalConsumo = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bed (1).png"))); // NOI18N
        jLabel1.setText(" Habitaciones");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        tablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaListado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 580, 450));

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancelar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 40, 30, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cargo Extra");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 140, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cargo Extra");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, -1, -1));

        cmbCargoExtra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbCargoExtra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCargoExtraItemStateChanged(evt);
            }
        });
        cmbCargoExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCargoExtraActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCargoExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 360, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. Habitacion");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 120, -1));

        cmbHabitacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbHabitacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbHabitacionItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 220, -1));

        btnEnviar.setBackground(new java.awt.Color(51, 153, 0));
        btnEnviar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, 110, 30));

        btnLimpiar.setBackground(new java.awt.Color(255, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 120, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Precio unitario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, 20));

        txtPrecioUnitario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(txtPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 360, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, -1, -1));

        txtCargo_id.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(txtCargo_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 140, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Cantidad");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, 30));

        txtCantidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 120, -1));

        lblTotalConsumo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTotalConsumo.setText("Total de consumo: ");
        getContentPane().add(lblTotalConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 100, -1));

        txtFecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 360, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoDetalle.jpg"))); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed
 
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HabitacionesRecepcion().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if(txtCargo_id.getText().equals("")){
            JOptionPane.showConfirmDialog(rootPane, "No hay datos en cliente");
            txtCargo_id.requestFocus();
            return;
        }
        
        
        
        if(txtCantidad.getText().equals("")){
            JOptionPane.showConfirmDialog(rootPane, "No ha ingresado una cantidad");
            txtCantidad.requestFocus();
            return;
        }
        if(txtPrecioUnitario.getText().equals("")){
            JOptionPane.showConfirmDialog(rootPane, "No hay datos en precio unitario");
            txtPrecioUnitario.requestFocus();
            return;
        }
        
        
        vCargoExtra dts = new vCargoExtra();
        fHabitacionesRecepcion_CargoExtra func = new fHabitacionesRecepcion_CargoExtra();
        
        //String selectNum = cmbHabitacion.getSelectedItem().toString();
        
        int numHabitacion = cmbHabitacion.getSelectedIndex();
        dts.setHabitacion_id(numHabitacion);
        
        int selectCargoE = cmbCargoExtra.getSelectedIndex();
        dts.setCce_cargoextra(selectCargoE);
        
        dts.setId_cargoextra(Integer.parseInt(txtCargo_id.getText()));
        dts.setCantidad_ce(Integer.parseInt(txtCantidad.getText()));
        dts.setCosto(Float.parseFloat(txtPrecioUnitario.getText()));
       
        dts.setFecha_ce(txtFecha.getText());
        
        if(func.insertar(dts)){
            JOptionPane.showMessageDialog(rootPane, "Cargo extra agregado satisfactoriamente");
            
            mostrar(numHabitacion);
            limpiar();
        }
        
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(!txtCargo_id.getText().equals("")){
            int confirm = JOptionPane.showConfirmDialog(rootPane, "¿Estás seguro de elimar este registro?");
            
            if(confirm == 0){
                fHabitacionesRecepcion_CargoExtra func = new fHabitacionesRecepcion_CargoExtra();
                vCargoExtra dts = new vCargoExtra();
                
                dts.setId_cargoextra(Integer.parseInt(txtCargo_id.getText()));
                func.eliminar(dts);
                int numHabitacion = cmbHabitacion.getSelectedIndex();
                mostrar(numHabitacion);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListadoMouseClicked
       

        
        int fila = tablaListado.rowAtPoint(evt.getPoint());
        
        txtCargo_id.setText(tablaListado.getValueAt(fila, 0).toString());
        

        txtCantidad.setText(tablaListado.getValueAt(fila, 2).toString());
        cmbHabitacion.setSelectedItem(tablaListado.getValueAt(fila, 3).toString());
        cmbCargoExtra.setSelectedItem(tablaListado.getValueAt(fila, 4).toString());
        txtPrecioUnitario.setText(tablaListado.getValueAt(fila, 5).toString());
        
        
        
    }//GEN-LAST:event_tablaListadoMouseClicked

    private void cmbHabitacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbHabitacionItemStateChanged
        
        
        //Pendiente
        if(evt.getStateChange() == ItemEvent.SELECTED){
            habitacion h = (habitacion) cmbHabitacion.getSelectedItem();
            try{
                
                DefaultTableModel modelo = new DefaultTableModel();
                tablaListado.setModel(modelo);
                
                PreparedStatement ps = null;
                ResultSet rs = null;
    
                conexion mysql = new conexion();
                Connection con = mysql.conectar();
                
                String SQL = "select * from cargoextra where habitacion_id_ce="+h.getId_habitacion();
                ps = con.prepareStatement(SQL);
                rs = ps.executeQuery();
                mostrar(h.getId_habitacion());
                
            } catch(Exception e){
                
            }
            
        }
    }//GEN-LAST:event_cmbHabitacionItemStateChanged

    private void cmbCargoExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCargoExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCargoExtraActionPerformed

    private void cmbCargoExtraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCargoExtraItemStateChanged

    }//GEN-LAST:event_cmbCargoExtraItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HabitacionesRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HabitacionesRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HabitacionesRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HabitacionesRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HabitacionesRecepcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbCargoExtra;
    private javax.swing.JComboBox<String> cmbHabitacion;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalConsumo;
    private javax.swing.JTable tablaListado;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCargo_id;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPrecioUnitario;
    // End of variables declaration//GEN-END:variables
}
